-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

-- TODO: manual review — top-level key 'preload = /home/leoh/Projects/HY4S/dotfiles/.config/hypr/Wallpapers/fantasy-knight-cat.jpg' has no enclosing section
-- TODO: manual review — top-level key 'wallpaper = ,/home/leoh/Projects/HY4S/dotfiles/.config/hypr/Wallpapers/fantasy-knight-cat.jpg' has no enclosing section
-- TODO: manual review — top-level key 'splash = false' has no enclosing section