preload = /home/leoh/Projects/HY4S/dotfiles/.config/hypr/Wallpapers/fantasy-knight-cat.jpg
wallpaper = ,/home/leoh/Projects/HY4S/dotfiles/.config/hypr/Wallpapers/fantasy-knight-cat.jpg
splash = false
