##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

# Example windowrule
# windowrule = float,class:^(kitty)$,title:^(kitty)$

# Ignore maximize requests from apps. You'll probably like this.
windowrule {
  name = windowrule-1
  suppress_event = maximize
  match:class = .*
}


# Fix some dragging issues with XWayland
windowrule {
  name = windowrule-2
  no_focus = on
  match:class = ^$
  match:title = ^$
  match:xwayland = 1
  match:float = 1
  match:fullscreen = 0
  match:pin = 0
}


# Float Wi-Fi settings
windowrule {
  name = windowrule-3
  float = on
  match:class = ^(nm-connection-editor)$
}

windowrule {
  name = windowrule-4
  float = on
  match:class = ^(Nm-connection-editor)$
}


# Float Bluetooth settings
windowrule {
  name = windowrule-5
  float = on
  match:class = ^(blueman-manager)$
}


#clipse
windowrule {
  name = windowrule-6
  float = on
  center = on
  size = 800 600
  match:class = ^(clipse-gui)$
}



